#!/usr/bin/env bash
set -euo pipefail

PROG=${0##*/}

usage(){
  cat <<EOF
Usage: $PROG --repo REPO_ROOT --patch-dir PATCH_DIR [--branch-prefix PREFIX] [--title TITLE] [--body BODY] [--remote REMOTE] [--create-pr]

Apply unified-diff patch files to a git repo on a new branch, push, and optionally open a PR via gh.
EOF
}

REPO=""
PATCH_DIR=""
BRANCH_PREFIX="mcp-patches"
TITLE="Automated patches"
BODY="Automated patches generated by MCP"
REMOTE="origin"
CREATE_PR=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2;;
    --patch-dir) PATCH_DIR="$2"; shift 2;;
    --branch-prefix) BRANCH_PREFIX="$2"; shift 2;;
    --title) TITLE="$2"; shift 2;;
    --body) BODY="$2"; shift 2;;
    --remote) REMOTE="$2"; shift 2;;
    --create-pr) CREATE_PR=1; shift;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown arg: $1"; usage; exit 2;;
  esac
done

if [[ -z "$REPO" || -z "$PATCH_DIR" ]]; then
  echo "--repo and --patch-dir are required" >&2
  usage
  exit 2
fi

cd "$REPO"
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Not a git repository: $REPO" >&2
  exit 3
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Working tree not clean; commit or stash changes first" >&2
  exit 4
fi

mapfile -t PATCHES < <(find "$PATCH_DIR" -type f \( -name '*.diff' -o -name '*.patch' \) -print 2>/dev/null || true)
if [[ ${#PATCHES[@]} -eq 0 ]]; then
  echo "No patch files found in $PATCH_DIR" >&2
  exit 5
fi

TS=$(date -u +%Y%m%dT%H%M%SZ)
BRANCH="${BRANCH_PREFIX}-${TS}"

git checkout -b "$BRANCH"

APPLIED=0
for p in "${PATCHES[@]}"; do
  echo "Applying patch: $p"
  if git apply --index "$p"; then
    echo "Applied $p"
    APPLIED=1
  else
    echo "git apply failed for $p, trying 3-way apply"
    if git apply --3way "$p"; then
      echo "3-way applied $p"
      APPLIED=1
    else
      echo "Failed to apply $p; copying to .hal_suggestions/patches for review"
      mkdir -p .hal_suggestions/patches
      cp -v "$p" .hal_suggestions/patches/ || true
    fi
  fi
done

if [[ $APPLIED -eq 0 ]]; then
  echo "No patches applied cleanly; aborting commit. Patches copied to .hal_suggestions/patches."
  git checkout -
  exit 6
fi

git add -A
git commit -m "$TITLE" || true
git push -u "$REMOTE" "$BRANCH"

if [[ "$CREATE_PR" -eq 1 && $(command -v gh || true) ]]; then
  if command -v gh >/dev/null 2>&1; then
    gh pr create --fill --title "$TITLE" --body "$BODY" || gh pr create --title "$TITLE" --body "$BODY"
  fi
else
  echo "Branch pushed: $REMOTE/$BRANCH"
  echo "Install GitHub CLI and re-run with --create-pr to open PR automatically"
fi

echo "Done"
exit 0
