#!/usr/bin/env python3
"""Create or update ~/.ansible/conf/env.yml and ensure vault password file.

Behaviour:
- Ensures `~/.ansible/conf/` exists (0700).
- Ensures vault password file `~/.ansible/conf/.vaultpass.txt` exists (0600).
- Prompts once for the local user's password to store as `user_password`.
- Optionally prompts for additional KEY=VALUE pairs (enter blank line to finish).
- Writes `env.yml` with the collected values (0600).
- If `ansible-vault` is available, offers to encrypt `env.yml` using the vault password file.

Usage:
  python3 scripts/configure_ansible_env.py [--no-encrypt] [--yes]
  Use from install script with `--reconfigure` to trigger interactive reconfiguration.
"""

from __future__ import annotations

import os
import sys
import stat
import re
import getpass
import secrets
import shutil
import subprocess
from pathlib import Path


def ensure_conf_dir() -> str:
    # Use standard path; if ANSIBLE_ENV_PATH set, derive conf dir from it
    env_path = os.getenv('ANSIBLE_ENV_PATH')
    if env_path:
        conf_dir = os.path.dirname(os.path.expanduser(env_path))
    else:
        conf_dir = os.path.expanduser('~/.ansible/conf')
    os.makedirs(conf_dir, exist_ok=True)
    # tighten permissions
    try:
        os.chmod(conf_dir, 0o700)
    except Exception:
        pass
    return conf_dir


def ensure_vault_pass_file(conf_dir: str) -> str:
    vp = os.path.join(conf_dir, '.vaultpass.txt')
    if not os.path.exists(vp):
        pw = ''.join(secrets.choice('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789') for _ in range(32))
        with open(vp, 'w', encoding='utf-8') as fh:
            fh.write(pw)
        os.chmod(vp, 0o600)
        print(f'Created vault password file: {vp}')
    else:
        try:
            os.chmod(vp, 0o600)
        except Exception:
            pass
    return vp


def load_existing_env(env_path: str) -> dict:
    """Load an existing env.yml into a dict. Try PyYAML, fallback to simple parser."""
    if not os.path.exists(env_path):
        return {}
    try:
        import yaml

        with open(env_path, 'r', encoding='utf-8') as fh:
            data = yaml.safe_load(fh) or {}
            if not isinstance(data, dict):
                return {}
            return data
    except Exception:
        # Simple fallback parser for basic YAML mappings and one-level sections
        data: dict = {}
        current_section = None
        with open(env_path, 'r', encoding='utf-8') as fh:
            for raw in fh:
                line = raw.rstrip('\n')
                if not line.strip() or line.strip().startswith('#'):
                    continue
                indent = len(line) - len(line.lstrip(' '))
                m_section = re.match(r'^([A-Za-z0-9_\-]+)\s*:\s*$', line.lstrip())
                m_kv = re.match(r'^([A-Za-z0-9_\-]+)\s*:\s*(.*)$', line.lstrip())
                if indent == 0 and m_section:
                    current_section = m_section.group(1)
                    data.setdefault(current_section, {})
                    continue
                if m_kv:
                    k = m_kv.group(1)
                    v = m_kv.group(2).strip()
                    # strip surrounding quotes
                    if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                        v = v[1:-1]
                    if indent > 0 and current_section:
                        data.setdefault(current_section, {})[k] = v
                    else:
                        data[k] = v
                    continue
                # otherwise ignore line
        return data


def write_env_yaml(conf_dir: str, combined: dict) -> str:
    env_path = os.path.join(conf_dir, 'env.yml')
    try:
        import yaml

        with open(env_path, 'w', encoding='utf-8') as fh:
            yaml.safe_dump(combined, fh, sort_keys=False)
    except Exception:
        with open(env_path, 'w', encoding='utf-8') as fh:
            fh.write('# Generated by scripts/configure_ansible_env.py\n')
            for k, v in combined.items():
                if isinstance(v, dict):
                    fh.write(f'{k}:\n')
                    for k2, v2 in v.items():
                        safe = str(v2).replace('"', '\\"')
                        fh.write(f'  {k2}: "{safe}"\n')
                else:
                    safe = str(v).replace('"', '\\"')
                    fh.write(f'{k}: "{safe}"\n')
    try:
        os.chmod(env_path, 0o600)
    except Exception:
        pass
    print(f'Wrote {env_path}')
    return env_path


def encrypt_with_ansible_vault(env_path: str, vault_file: str) -> bool:
    ansible_vault = shutil.which('ansible-vault')
    if not ansible_vault:
        print('ansible-vault not found on PATH; skipping encryption')
        return False
    cmd = [ansible_vault, 'encrypt', '--vault-password-file', vault_file, env_path]
    try:
        subprocess.check_call(cmd)
        print('Encrypted env.yml with ansible-vault')
        return True
    except subprocess.CalledProcessError as e:
        print(f'ansible-vault encrypt failed: {e}')
        return False


def main() -> int:
    no_encrypt = False
    auto_yes = False
    args = sys.argv[1:]
    while args:
        a = args.pop(0)
        if a == '--no-encrypt':
            no_encrypt = True
        elif a in ('--yes', '-y'):
            auto_yes = True
        else:
            print('Unknown arg:', a)
            return 2

    conf_dir = ensure_conf_dir()
    vault_file = ensure_vault_pass_file(conf_dir)

    env_path = os.path.join(conf_dir, 'env.yml')
    existing_env = load_existing_env(env_path)

    # Determine a section name for this repository (allow override via env var)
    section_name = os.getenv('ANSIBLE_ENV_SECTION') or Path(os.getcwd()).name.replace('-', '_')

    print('\nThis will configure runtime variables for mcp-rhel-manager.')
    print('Values are stored in: ', env_path)
    if not auto_yes:
        resp = input('Proceed to configure now? [Y/n]: ').strip().lower()
        if resp and resp not in ('y', 'yes'):
            print('Aborted.')
            return 1

    # Merge existing top-level keys and section keys; top-level takes precedence
    merged: dict[str, str] = {}
    for k, v in existing_env.items():
        if not isinstance(v, dict):
            merged[k] = v
    sec_vals = {}
    if isinstance(existing_env.get(section_name), dict):
        sec_vals = existing_env.get(section_name, {})
        for k, v in sec_vals.items():
            if k not in merged:
                merged[k] = v

    data: dict[str, str] = {}
    # Use existing value if present; otherwise prompt once
    if merged.get('user_password'):
        data['user_password'] = merged.get('user_password')
        print('Using existing user_password from env.yml')
    else:
        try:
            passwd = getpass.getpass(f'Enter password for user {os.environ.get("USER", "<user>")}: ')
        except Exception:
            passwd = ''
        data['user_password'] = passwd

    # Prompt for additional KEY=VALUE pairs only if they are not already present
    print('\nEnter any additional variables as KEY=VALUE. Leave blank to finish.')
    while True:
        try:
            line = input('VAR=VALUE: ').strip()
        except EOFError:
            break
        if not line:
            break
        if '=' not in line:
            print('Invalid format, expected KEY=VALUE')
            continue
        k, v = line.split('=', 1)
        k = k.strip()
        v = v.strip()
        if not k:
            print('Empty key, skipping')
            continue
        # If key already exists in merged, keep existing and skip prompting
        if k in merged:
            print(f'Skipping {k}; already present in env.yml')
            continue
        data[k] = v

    # Merge changes into existing_env under the repo-specific section, and also write top-level keys if missing
    existing_env.setdefault(section_name, {})
    existing_env[section_name].update(data)
    for k, v in data.items():
        if k not in existing_env:
            existing_env[k] = v

    env_path = write_env_yaml(conf_dir, existing_env)

    if not no_encrypt:
        if auto_yes:
            do_encrypt = True
        else:
            ans = input('Encrypt env.yml with ansible-vault using vault pass file? [Y/n]: ').strip().lower()
            do_encrypt = (ans == '' or ans in ('y', 'yes'))
        if do_encrypt:
            encrypt_with_ansible_vault(env_path, vault_file)

    print('\nConfiguration complete. To reconfigure later run:')
    print('  python3 scripts/configure_ansible_env.py')
    print('Keep the vault password file secret:', vault_file)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
