#!/usr/bin/env bash
set -euo pipefail

PROG=${0##*/}

usage(){
  cat <<EOF
Usage: $PROG --repo REPO_ROOT --src-dir SUGGESTIONS_DIR [--dest-dir DEST] [--branch-prefix PREFIX] [--title TITLE] [--body BODY] [--remote REMOTE] [--create-pr]

Copies suggestion files into the repo, commits them on a new branch, pushes, and optionally opens a PR.
EOF
}

REPO=""
SRC_DIR=""
DEST_DIR=".hal_suggestions/patches"
BRANCH_PREFIX="mcp-suggestions"
TITLE="Automated suggestions"
BODY="Automated suggestions generated by MCP"
REMOTE="origin"
CREATE_PR=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2;;
    --src-dir) SRC_DIR="$2"; shift 2;;
    --dest-dir) DEST_DIR="$2"; shift 2;;
    --branch-prefix) BRANCH_PREFIX="$2"; shift 2;;
    --title) TITLE="$2"; shift 2;;
    --body) BODY="$2"; shift 2;;
    --remote) REMOTE="$2"; shift 2;;
    --create-pr) CREATE_PR=1; shift;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown arg: $1"; usage; exit 2;;
  esac
done

if [[ -z "$REPO" || -z "$SRC_DIR" ]]; then
  echo "--repo and --src-dir are required" >&2
  usage
  exit 2
fi

cd "$REPO"
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Not a git repository: $REPO" >&2
  exit 3
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Working tree not clean; commit or stash changes first" >&2
  exit 4
fi

if [[ ! -d "$SRC_DIR" ]]; then
  echo "Suggestions directory not found: $SRC_DIR" >&2
  exit 5
fi

TS=$(date -u +%Y%m%dT%H%M%SZ)
BRANCH="${BRANCH_PREFIX}-${TS}"

git checkout -b "$BRANCH"

# ensure dest dir exists in repo
mkdir -p "$DEST_DIR"

# copy suggestions into repo dest dir
cp -av "$SRC_DIR"/* "$DEST_DIR/" || true

git add -A "$DEST_DIR"
git commit -m "$TITLE" || true
git push -u "$REMOTE" "$BRANCH"

if [[ "$CREATE_PR" -eq 1 && $(command -v gh || true) ]]; then
  if command -v gh >/dev/null 2>&1; then
    gh pr create --fill --title "$TITLE" --body "$BODY" || gh pr create --title "$TITLE" --body "$BODY"
  fi
else
  echo "Branch pushed: $REMOTE/$BRANCH"
  echo "Install GitHub CLI and re-run with --create-pr to open PR automatically"
fi

  # If requested to create PR but GH CLI not available, try GitHub API using GITHUB_TOKEN
  if [[ "$CREATE_PR" -eq 1 && -z "$(command -v gh || true)" && -n "${GITHUB_TOKEN:-}" ]]; then
    echo "Creating PR via GitHub API..."
    repo=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null || true)
    # fallback to environment GH_REPOSITORY
    OWNER_REPO="${GITHUB_REPOSITORY:-$(git config --get remote.${REMOTE}.url | sed -n 's#.*github.com[:/]\([^/]*\/[^/.]*\).*#\1#p')}"
    if [[ -z "$OWNER_REPO" ]]; then
      echo "Unable to determine repository for API PR creation" >&2
    else
      api_url="https://api.github.com/repos/$OWNER_REPO/pulls"
      head_branch="$BRANCH"
      data=$(jq -n --arg t "$TITLE" --arg b "$BODY" --arg head "$head_branch" --arg base "main" '{title:$t, body:$b, head:$head, base:$base, draft:true}')
      resp=$(curl -sS -X POST "$api_url" -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type: application/json" -d "$data")
      echo "$resp"
    fi
  fi

echo "Done"
exit 0
