#!/usr/bin/env bash
set -euo pipefail

PROG=${0##*/}

usage(){
  cat <<EOF
Usage: $PROG --repo REPO_ROOT --patch PATCH_FILE [--branch-prefix PREFIX] [--title TITLE] [--body BODY] [--remote REMOTE] [--create-pr]

Creates a branch, applies a patch, commits, pushes, and opens a PR using the GitHub CLI if available.
EOF
}

REPO=""
PATCH=""
BRANCH_PREFIX="mcp-fix"
TITLE="LLM suggested fix"
BODY="Automated suggestion generated by MCP LLM pipeline"
REMOTE="origin"
CREATE_PR=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2;;
    --patch) PATCH="$2"; shift 2;;
    --branch-prefix) BRANCH_PREFIX="$2"; shift 2;;
    --title) TITLE="$2"; shift 2;;
    --body) BODY="$2"; shift 2;;
    --remote) REMOTE="$2"; shift 2;;
    --create-pr) CREATE_PR=1; shift;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown arg: $1"; usage; exit 2;;
  esac
done

if [[ -z "$REPO" || -z "$PATCH" ]]; then
  echo "--repo and --patch are required" >&2
  usage
  exit 2
fi

cd "$REPO"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Not a git repository: $REPO" >&2
  exit 3
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Working tree not clean; commit or stash changes first" >&2
  exit 4
fi

TS=$(date -u +%Y%m%dT%H%M%SZ)
BRANCH="${BRANCH_PREFIX}-${TS}"

git checkout -b "$BRANCH"

if git apply --index "$PATCH"; then
  echo "Applied patch with git apply"
else
  echo "git apply failed, trying 3-way apply"
  git apply --3way "$PATCH"
fi

git add -A
git commit -m "$TITLE" || true

git push -u "$REMOTE" "$BRANCH"

if [[ "$CREATE_PR" -eq 1 && $(command -v gh || true) ]]; then
  if command -v gh >/dev/null 2>&1; then
    gh pr create --fill --title "$TITLE" --body "$BODY" || gh pr create --title "$TITLE" --body "$BODY"
  fi
else
  echo "Branch pushed: $REMOTE/$BRANCH"
  echo "Create a PR manually or install GitHub CLI and run with --create-pr"
fi

echo "Done"
exit 0
